# type conversion
i1=input("enter a number:")
print(type(i1))
print(i1)
print(type(int(i1)))
print(int(i1))
print(type(float(i1)))
print(float(i1))
print(type(complex(i1)))
print(complex(i1))

i1=int(input("enter a number:"))
print(type(i1))
print(i1)
print(type(str(i1)))
print(str(i1))
print(type(float(i1)))
print(float(i1))
print(type(complex(i1)))
print(complex(i1))

i1=float(input("enter a number:"))
print(type(i1))
print(i1)
print(type(str(i1)))
print(str(i1))
print(type(int(i1)))
print(int(i1))
print(type(complex(i1)))
print(complex(i1))

i1=complex(input("enter a number:"))
print(type(i1))
print(i1)
print(type(str(i1)))
print(str(i1))